name: Deploy verb app

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container: node:16.14.2

    steps:
      - uses: actions/checkout@v1

      - name: init yarn
        run: npm install yarn -g

      - name: init aws
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://test-bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_VALUE }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
