name: Deploy verb app

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://test-bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_VALUE }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
